# .github/workflows/commitlint.yml
name: Commitlint
on:
  pull_request:
    branches: [ master ]  # ou main

jobs:
  lint-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - run: npm i -D @commitlint/cli @commitlint/config-conventional
      - run: npx commitlint --from origin/${{ github.base_ref }} --to HEAD
